name: "\U0001F41E Bug report"
description: Report an issue with Vite
labels: [pending triage]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: reproduction
    attributes:
      label: Reproduction
      description: Please provide a link via [vite.new](https://vite.new/) or a link to a repo that can reproduce the problem you ran into. `npm create vite@latest` and `npm create vite-extra@latest` (for SSR or library repros) can be used as a starter template. A [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) is required ([Why?](https://antfu.me/posts/why-reproductions-are-required)). If a report is vague (e.g. just a generic error message) and has no reproduction, it will receive a "needs reproduction" label. If no reproduction is provided after 3 days, it will be auto-closed.
      placeholder: Reproduction URL
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the issue
      description: Is it a bug or a feature request (new component, new icon, new CSS class)?
      placeholder: A bug where...
    validations:
      required: true
  - type: input
    id: specific-component
    attributes:
      label: Is this issue related to a specific component, variant, and/or state? If so, please detail which.
      description: Page Header > Voice > Cancelled
      placeholder: Directory > Component
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Are any specific browsers impacted by this bug?
      description: Chrome, Edge, Firefox, Safari, etc.
      placeholder: Chrome 56 on macOS 11.2
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Which version of the Salesforce Lightning Design System are you using?
      description: If you're not sure, be specific about the environment: e.g. The bug happens in Visualforce when importing SLDS via `<apex:slds />` in a Spring ’17 org.
      placeholder: 2.2.2
    validations:
      required: true
  - type: textarea
    id: expect-happen
    attributes:
      label: What did you expect to happen?
      description: Long text wraps on multiple lines
      placeholder: Something...
  - type: textarea
    id: actually-happen
    attributes:
      label: What actually happened?
      description: Long text wraps on multiple lines
      placeholder: Something...
